### ISSUE TITLE
Optional: use spread operator

### ISSUE THREAD

**Issue by rudnitskih** [ArtemChubatyi/cryptoKittensReact#10]
instead of this you can do:

![image](https://user-images.githubusercontent.com/8848858/51236192-3953ab80-197a-11e9-8130-58d98caf4920.png)

`const {name, category} = kitten`
// 50 lines of code

`<div>{name}</div>`

**Comment by ArtemChubatyi** [comment]
![image](https://user-images.githubusercontent.com/43701381/51252857-8f8a1400-19a5-11e9-9943-5dbf9343c40b.png)
@rudnitskih

**Comment by ArtemChubatyi** [comment]
Только, ты, похоже, писал одно, а имел ввиду другое:
![image](https://user-images.githubusercontent.com/43701381/51252981-dbd55400-19a5-11e9-829b-41e68cb3135c.png)

![image](https://user-images.githubusercontent.com/43701381/51252957-d0822880-19a5-11e9-9557-e55f59a1dc4b.png)

**Comment by rudnitskih** [comment]
Да иммел ввиду деструктуризацию, сорри.
